### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by ilker-aktuna** [kyuz0/amd-strix-halo-comfyui-toolboxes#22]
thanks for this toolbox but I have 2 issues: 

1. I get a very long prompt when I enter the toolbox: 

08;start=34d8c021-a9ab-4e72-8892-61cc5bd10c64;machineid=c1265bf0e18f455f932767a78f40cd92;user=aadmin;hostname=toolbox;bootid=badecba1-ec7c-403d-a8ec-3238d57ee757;pid=90611;type=shell;cwd=/home/aadminaadmin@toolbox:~$ 
08;end=320065b5-1a9c-4d5d-bae0-7f0fde6afd69;exit=success08;start=34d8c021-a9ab-4e72-8892-61cc5bd10c64;machineid=c1265bf0e18f455f932767a78f40cd92;user=aadmin;hostname=toolbox;bootid=badecba1-ec7c-403d-a8ec-3238d57ee757;pid=90611;type=shell;cwd=/home/aadminaadmin@toolbox:~$             

2. when I run commfyui , it fails:
```

lbox:~$ start_comfy_ui
08;start=d74069d4-7c77-4c2e-ba2b-653763a156d0;machineid=c1265bf0e18f455f932767a78f40cd92;user=aadmin;hostname=toolbox;bootid=badecba1-ec7c-403d-a8ec-3238d57ee757;pid=90611;type=command;cwd=/home/aadminAdding extra search path text_encoders /home/aadmin/comfy-models/text_encoders
Adding extra search path vae /home/aadmin/comfy-models/vae
Adding extra search path checkpoints /home/aadmin/comfy-models/checkpoints
Adding extra search path diffusion_models /home/aadmin/comfy-models/diffusion_models
Adding extra search path unet /home/aadmin/comfy-models/unet
Adding extra search path loras /home/aadmin/comfy-models/loras
Adding extra search path latent_upscale_models /home/aadmin/comfy-models/latent_upscale_models
Adding extra search path clip_vision /home/aadmin/comfy-models/clip_vision
Setting output directory to: /home/aadmin/comfy-outputs
Checkpoint files will always be loaded safely.
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend cuda: {'available': False, 'disabled': True, 'unavailable_reason': 'CUDA not available on this system', 'capabilities': []}
Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': 'CUDA not available on this system', 'capabilities': []}
Traceback (most recent call last):
  File "/opt/ComfyUI/[main.py](javascript:void(0);)", line 179, in <module>
    import execution
  File "/opt/ComfyUI/[execution.py](javascript:void(0);)", line 18, in <module>
    import comfy.model_management
  File "/opt/ComfyUI/comfy/model_[management.py](javascript:void(0);)", line 251, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ~~~~~~~~~~~~~~~~^^
  File "/opt/ComfyUI/comfy/model_[management.py](javascript:void(0);)", line 201, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/venv/lib64/python3.13/site-packages/torch/cuda/__init__.py", line 1151, in current_device
    _lazy_init()
    ~~~~~~~~~~^^
  File "/opt/venv/lib64/python3.13/site-packages/torch/cuda/__init__.py", line 481, in _lazy_init
    torch._C._cuda_init()
    ~~~~~~~~~~~~~~~~~~~^^
RuntimeError: No CUDA GPUs are available
08;end=d74069d4-7c77-4c2e-ba2b-653763a156d0;exit=failure;status=108;start=34d8c021-a9ab-4e72-8892-61cc5bd10c64;machineid=c1265bf0e18f455f932767a78f40cd92;user=aadmin;hostname=toolbox;bootid=badecba1-ec7c-403d-a8ec-3238d57ee757;pid=90611;type=shell;cwd=/opt/ComfyUIaadmin@toolbox:/opt/ComfyUI$
```

I have read the other thread about this issue. some users swapped to docker as a solution. But I don't know how to run this container as docker. is there a guide ?

**Comment by szma** [comment]
I fixed it by using the crun runtime after I suddently got the same issue.

I create my toolbox doing:

```
distrobox create \
                   --name amd-strix-halo-comfyui \
                   --image docker.io/kyuz0/amd-strix-halo-comfyui:latest \
                   --additional-flags "--runtime /usr/bin/crun --device /dev/dri --device /dev/kfd --group-add keep-groups --security-opt seccomp=unconfined"
```

After installing crun on the host system.
