### ISSUE TITLE
start_comfy_ui on AMD 395, ROCm 7.2, Ubuntu 25.10, Kernel 6.17

### ISSUE THREAD

**Issue by edasque** [kyuz0/amd-strix-halo-comfyui-toolboxes#9]
I am getting an odd errror (considering the requirement). I am on Ubuntu 25.10, ROCm 7.2.

This might be an indication of the problem (the unknown GPU).

```
AMD Ryzen AI Max “Strix Halo” — Image & Video Toolbox (gfx1151, ROCm via TheRock)
ROCm nightly: 7.12.0a20260211

Machine: Framework Desktop (AMD Ryzen AI Max 300 Series)
GPU    : Unknown AMD GPU

Repo   : https://github.com/kyuz0/amd-strix-halo-comfyui-toolboxes
Image  : docker.io/kyuz0/amd-strix-halo-comfyui:latest
```

When I `start_comfy_ui`:
```
Adding extra search path text_encoders /home/ed/comfy-models/text_encoders
Adding extra search path vae /home/ed/comfy-models/vae
Adding extra search path checkpoints /home/ed/comfy-models/checkpoints
Adding extra search path diffusion_models /home/ed/comfy-models/diffusion_models
Adding extra search path unet /home/ed/comfy-models/unet
Adding extra search path loras /home/ed/comfy-models/loras
Adding extra search path latent_upscale_models /home/ed/comfy-models/latent_upscale_models
Adding extra search path clip_vision /home/ed/comfy-models/clip_vision
Setting output directory to: /home/ed/comfy-outputs
Checkpoint files will always be loaded safely.
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': 'CUDA not available on this system', 'capabilities': []}
Found comfy_kitchen backend cuda: {'available': False, 'disabled': True, 'unavailable_reason': 'CUDA not available on this system', 'capabilities': []}
Traceback (most recent call last):
  File "/opt/ComfyUI/main.py", line 179, in <module>
    import execution
  File "/opt/ComfyUI/execution.py", line 18, in <module>
    import comfy.model_management
  File "/opt/ComfyUI/comfy/model_management.py", line 251, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ~~~~~~~~~~~~~~~~^^
  File "/opt/ComfyUI/comfy/model_management.py", line 201, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/venv/lib64/python3.13/site-packages/torch/cuda/__init__.py", line 1151, in current_device
    _lazy_init()
    ~~~~~~~~~~^^
  File "/opt/venv/lib64/python3.13/site-packages/torch/cuda/__init__.py", line 481, in _lazy_init
    torch._C._cuda_init()
    ~~~~~~~~~~~~~~~~~~~^^
RuntimeError: No CUDA GPUs are available
```

**Comment by edasque** [comment]
Something about /dev/kfd being mapped to the nobody group - something I am not a part of within the toolbox. Maybe a Ubuntu/Fedora difference. investgiating further.

**Comment by edasque** [comment]
After extensive troubleshooting, here are the key issues preventing GPU access in toolboxes on Ubuntu:

### 1. **`toolbox create` doesn't support device flags**
- You cannot pass `--device /dev/kfd` or other GPU device flags during toolbox creation
- Toolbox is a wrapper around podman with limited flag support

### 2. **Insufficient container privileges**
- Even after manually fixing groups inside a toolbox, the container lacks necessary privileges to access `/dev/kfd`
- Requires `--privileged` and `--security-opt label=disable` flags that toolbox doesn't expose
- Even `sudo` cannot access `/dev/kfd` inside a standard toolbox

### 3. **Device ownership remapping**
- Inside containers, GPU devices get remapped to `65534:65534` (nobody:nobody)
- This happens regardless of host ownership (`root:render` on host)

### 4. **Group ID mismatches (Ubuntu-specific)**
- **Host (Ubuntu):** `render=991`, `video=44`
- **Container:** `render=105`, `video=39`, `nobody=65534`
- Ubuntu and Fedora/RHEL use different group ID conventions
- Toolbox is designed for Fedora/RHEL where group IDs are more standardized


It looks like I could get it working with podman directly but I am not well versed in podman, can I use docker instead, you think?

**Comment by alexpatcas** [comment]
I've gotten around it by using distrobox

**Comment by guangchenli** [comment]
Seems like how podman handle group id is different from that of docker. I fixed this problem by switching to docker instead.

**Comment by ejumper** [comment]
I'm also on Ubuntu 25.10 using distrobox. It seems like others were able to get it to work with distrobox, but I was unable to get the --privileged and --security-op flags to register, tried a bunch of stuff, but render permissions stayed nobody:nobody

I eventually just changed the render group permissions (chmod 666 on /dev/kfd /dev/dri/renderD128) not ideal, but it gets it working. If you do this just don't forget to make a udev rule to make it perminent.

**Comment by ilker-aktuna** [comment]
well, I have the same issue. how can I switch to docker ? 
(in fact I prefer docker  since I also use it for other projects )

**Comment by edasque** [comment]
I used the following on Ubuntu 24.04 with recent docker:
```
  amd-strix-halo-comfyui:
    command: '/bin/bash -c "source /opt/venv/bin/activate && python /opt/ComfyUI/main.py --listen 0.0.0.0 --port 8188 --disable-mmap --gpu-only --disable-smart-memory --cache-none --bf16-vae"'
    environment:
      - TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
      - TORCH_BLAS_PREFER_HIPBLASLT=1
    image: 'kyuz0/amd-strix-halo-comfyui:latest'
    ports:
      - '8188:8188'
    volumes:
      - '/home/ed/comfy-input:/opt/ComfyUI/input'
      - '/home/ed/comfy-output:/opt/ComfyUI/output'
      - '/home/ed/comfy-nodes:/opt/ComfyUI/custom_nodes'
      - '/home/ed/comfy-models:/opt/ComfyUI/models'
      - '/home/ed/comfy-workflows:/opt/ComfyUI/user/default/workflows'
      - '/home/ed/comfy-venv:/opt/venv'
    shm_size: 16gb
    security_opt:
      - seccomp=unconfined
    group_add:
      - render
      - video
    devices:
      - /dev/kfd
      - /dev/dri
    restart: unless-stopped
    container_name: comfyui
```

I decided to externalize the workflows so you might have to copy the ones from the image to the external volume mapping if you want to do the same as I did.
